### ISSUE TITLE
Error while calling lua chunk

### ISSUE THREAD

**Issue by flechtwerkflechtwerk** [madskjeldgaard/reaper-nvim#1]
Hey,

I succesfully installed reaper-nvim via vim-plug, but the command 
`lua require'reaper-nvim'.setup()`
results in:

E5105: Error while calling lua chunk: .../USER_NAME/.vim/plugged/reaper-nvim//lua/reaper-nvim/utils.lua:1: attempt to index field 'g' (a nil value)

(I changed my user name to USER_NAME above.)
Could it be the double '//' in the path? Unfortunately I'm not familiar with Lua myself so I wouldn't tinker with the code.

Many thanks! This plugin looks awesome by the way - so I hope I can get it to work :)

**Comment by madskjeldgaard** [comment]
Hi @flechtwerkflechtwerk . Thanks for trying it out and for your bug report.

It sounds to me like you are not on NVIM v0.5. Can you check your version and post it here? ```nvim --version``` . Thanks!

The plugin is for v0.5 which is still in development but should be out soon enough, it contains huge improvements to the LUA capability of NVIM which this plugin makes use of. 

Thanks!

**Comment by flechtwerkflechtwerk** [comment]
Hey @madskjeldgaard , thanks for the quick reply! You were right - I was not on v0.5 yet. I switched to the git version of nvim and everything works perfectly now.

Thanks again for this plugin (and the accompagning osccli), this is very useful!

**Comment by madskjeldgaard** [comment]
That's great! Let me know if you experience any bugs or have feature requests. It's still early days for this silly and fun plugin
