### ISSUE TITLE
Reaper's config for receiving the osc commands?

### ISSUE THREAD

**Issue by AntoineBalaine** [madskjeldgaard/reaper-nvim#4]
Hello, 

Could you share some details about setting up the reaper side for receiving the osc commands? 

At the moment, just setting up the neovim plugin and calling commands doesn't yield anything…

**Comment by madskjeldgaard** [comment]
<img width="720" alt="Screenshot 2023-12-20 at 16 08 18" src="https://github.com/madskjeldgaard/reaper-nvim/assets/22474608/ceffdc69-186f-42e3-a75e-7f8120b3e05c">
<img width="633" alt="Screenshot 2023-12-20 at 16 08 24" src="https://github.com/madskjeldgaard/reaper-nvim/assets/22474608/aceeb44a-a2f5-467d-b79a-6119e5cbcd86">

here's how I've set it up. let me know if it works!

**Comment by AntoineBalaine** [comment]
OSC works like a charm, thank you very much!

Side note, I'm seeing this error in the console whenever I call an action from ReaFuzz:
```
reaper-nvim/lua/reaper-nvim.lua:18>
Error detected while processing function 19[30]..<SNR>23_callback[25]..function 19[30]..<SNR>23_callback:
line   23:
Vim(call):E718: Funcref required
```
The actions still run just fine, just thought you might want to know.

Thank you for making this awesome plugin!

**Comment by AntoineBalaine** [comment]
I have another question:
Is there any way to pass commandIDs that aren't integers? Adding a function to your plugin: 
```lua
function M.reaper_action(action_id)
 utils.send_action_osc(action_id)
end
```
and then from my lua config:
```lua
function CallReaperAction()
    local reaper_nvim = require 'reaper-nvim'
        local scriptId = "_RSbff5adaa2f20b1abb3d4da0cf4e4c30fccc7c88a"
        reaper_nvim.reaper_action(scriptId)
end
```
I'm trying to pass some reaper-scripts commandIds, but it always seems to fail validation from OSC package.  
```bash
osc.nvim/lua/osc/lib/losc/lib/struct.lua:45: attempt to perform arithmetic on local 'val' (a nil value)
```
